"""
DQN.py
------
Vanilla Deep Q-Network trading agent (no dueling / prioritized replay / anything
non-standard). This is a fixed and tuned version of the DQN implemented in the
FinSearch notebook, which was underperforming a simple ARIMA baseline.

WHAT WAS WRONG BEFORE, AND WHAT CHANGED
========================================
1. TRAIN/TEST LEAKAGE + MISALIGNED EVALUATION
   The notebook trained the agent on `df_features` (the *entire* series) and then
   also generated the evaluation actions by replaying the policy over that same
   full series, before finally slicing the signals against `test_prices` from
   `feature_engineering`. That means the agent partly memorised the test period
   during training, and the action list wasn't actually derived from the test
   split the backtester was comparing against. Here the agent is trained ONLY on
   `train_series` and the action list fed to the backtester is generated by a
   separate, greedy (epsilon=0) pass over `test_series`, so evaluation matches
   `test_prices` like the ARIMA baseline does.

2. UNNORMALISED, MIXED-SCALE STATE
   Price/SMA_5/SMA_20 sit in the thousands while Momentum/Volatility sit near
   zero. Feeding that straight into a 2-layer MLP makes gradients dominated by
   the large-scale features and slows/prevents convergence. States are now
   z-score normalised using statistics computed on the TRAINING split only
   (no leakage), and those same stats are reused at test time.

3. RAW-RUPEE REWARD -> HUGE, UNSTABLE Q-TARGETS
   Reward was `net_worth_t - net_worth_t-1`, i.e. raw rupee P&L on a ₹100,000
   book. That gives rewards in the hundreds/thousands, blowing up Q-values and
   the MSE loss, and makes the discount horizon effectively meaningless.
   Reward is now the daily PERCENTAGE return of the portfolio, scaled by 100
   (so it behaves like "% return in basis-point-ish units"), which keeps
   targets small and stable regardless of the price level.

4. LOSS / OPTIMISATION STABILITY
   Switched MSE -> Huber loss (SmoothL1Loss), which is standard vanilla-DQN
   practice for reducing sensitivity to reward outliers, and added gradient
   clipping. Still a single, plain feed-forward Q-network -- no dueling heads,
   no prioritized replay, no double-DQN target trick.

5. TRAINING SCHEDULE
   50 episodes with epsilon_decay=0.995 barely explores past epsilon~0.78 by
   the end, so the greedy policy used for evaluation was never really tested
   during training. Episodes were increased and epsilon decay tuned so the
   agent spends real time near-greedy before we freeze the policy, and the
   BEST-performing training episode's weights are checkpointed and restored
   for evaluation (a purely vanilla, no-architecture-change safeguard against
   ending training on a locally bad epsilon-greedy episode).

Everything else (environment mechanics: all-in/all-out Sell/Hold/Buy, the
imports, and the way results are handed to `backtester`) is kept the same as
the notebook so this is a drop-in replacement.
"""

import copy
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from collections import deque

from backtest import backtester
from feature_engineering import train_series, test_series, train_prices, test_prices

# ----------------------------------------------------------------------------
# Setup
# ----------------------------------------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

STATE_FEATURES = ['Price', 'SMA_5', 'SMA_20', 'Momentum_5', 'Momentum_10', 'Volatility_10']


# ----------------------------------------------------------------------------
# Feature engineering
# ----------------------------------------------------------------------------
# `train_series` / `test_series` from feature_engineering.py are just the raw
# LogReturns series -- they don't carry SMA/Momentum/Volatility columns. We
# rebuild those features here from `train_prices` / `test_prices` (the "Open"
# price levels), since SMA/Momentum/Volatility are naturally defined on price
# levels, not log-returns.
#
# The features are computed on the CONTINUOUS price series (train followed by
# test) so the first rows of the test split still have a valid rolling window
# (looking back into the tail of the training data, which is legitimate -- a
# live trading system would have that history available too), instead of
# being NaN/dropped right at the test boundary.
def build_feature_frame(prices):
    df = pd.DataFrame({'Price': prices.astype(np.float64)})
    df['SMA_5'] = df['Price'].rolling(window=5).mean()
    df['SMA_20'] = df['Price'].rolling(window=20).mean()
    df['Momentum_5'] = df['Price'].pct_change(periods=5)
    df['Momentum_10'] = df['Price'].pct_change(periods=10)
    df['Volatility_10'] = df['Price'].rolling(window=10).std()
    return df


_full_prices = pd.concat([train_prices, test_prices])
_full_prices = _full_prices[~_full_prices.index.duplicated(keep='first')].sort_index()

_full_features = build_feature_frame(_full_prices).dropna()
for _col in STATE_FEATURES:
    _full_features[_col] = _full_features[_col].astype(np.float32)

# Split the engineered features back out using the original train/test price
# indices, so alignment with `test_prices` (used by the backtester) is exact.
train_features_df = _full_features.loc[_full_features.index.isin(train_prices.index)].reset_index(drop=True)
test_features_df = _full_features.loc[_full_features.index.isin(test_prices.index)].reset_index(drop=True)

print(f"Train feature rows: {len(train_features_df)} | Test feature rows: {len(test_features_df)}")

# Normalisation stats computed ONLY on the training split so there is no
# lookahead into the test period.
_train_stats_df = train_features_df[STATE_FEATURES].astype(np.float64)
STATE_MEAN = _train_stats_df.mean().values.astype(np.float32)
STATE_STD = _train_stats_df.std().replace(0, 1e-6).values.astype(np.float32)


# ----------------------------------------------------------------------------
# Environment (same mechanics as the notebook: full balance in/out, next-day
# fill, reward derived from the resulting net worth change)
# ----------------------------------------------------------------------------
class StockTradingEnv:
    def __init__(self, dataframe, initial_balance=100000, reward_scale=100.0):
        self.df = dataframe.reset_index(drop=True)
        self.initial_balance = initial_balance
        self.state_features = STATE_FEATURES
        self.reward_scale = reward_scale
        self.reset()

    def reset(self):
        self.current_step = 0
        self.balance = self.initial_balance
        self.shares_held = 0
        self.net_worth = self.initial_balance
        return self._get_state()

    def _get_state(self):
        raw = self.df.loc[self.current_step, self.state_features].values.astype(np.float32)
        norm = (raw - STATE_MEAN) / STATE_STD
        return norm.astype(np.float32)

    def step(self, action):
        current_price = self.df.loc[self.current_step, 'Price']

        # 0: Sell, 1: Hold, 2: Buy
        if action == 2:
            if self.balance > 0:
                self.shares_held += self.balance / current_price
                self.balance = 0
        elif action == 0:
            if self.shares_held > 0:
                self.balance += self.shares_held * current_price
                self.shares_held = 0

        self.current_step += 1
        done = self.current_step >= len(self.df) - 1

        next_price = self.df.loc[self.current_step, 'Price']
        new_net_worth = self.balance + (self.shares_held * next_price)

        # Percentage-return reward instead of raw rupee delta -- keeps reward
        # magnitude stable and comparable throughout training.
        pct_return = (new_net_worth - self.net_worth) / (self.net_worth + 1e-8)
        reward = pct_return * self.reward_scale

        self.net_worth = new_net_worth
        next_state = self._get_state() if not done else None

        return next_state, reward, done


# ----------------------------------------------------------------------------
# Q-Network (plain vanilla MLP, unchanged shape of architecture)
# ----------------------------------------------------------------------------
class QNetwork(nn.Module):
    def __init__(self, state_dim, action_dim):
        super(QNetwork, self).__init__()
        self.fc = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, action_dim)
        )

    def forward(self, x):
        return self.fc(x)


# ----------------------------------------------------------------------------
# Replay buffer
# ----------------------------------------------------------------------------
class ReplayBuffer:
    def __init__(self, capacity=20000):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        state, action, reward, next_state, done = zip(*random.sample(self.buffer, batch_size))
        return (
            np.array(state, dtype=np.float32),
            np.array(action, dtype=np.int64),
            np.array(reward, dtype=np.float32),
            np.array(next_state, dtype=np.float32),
            np.array(done, dtype=np.float32)
        )

    def __len__(self):
        return len(self.buffer)


# ----------------------------------------------------------------------------
# DQN Agent (vanilla: single online net + single target net, hard updates)
# ----------------------------------------------------------------------------
class DQNAgent:
    def __init__(self, state_dim, action_dim, lr=5e-4, gamma=0.99,
                 epsilon=1.0, epsilon_decay=0.97, epsilon_min=0.02,
                 min_replay_size=1000):
        self.state_dim = state_dim
        self.action_dim = action_dim
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min
        self.min_replay_size = min_replay_size

        self.policy_net = QNetwork(state_dim, action_dim).to(device)
        self.target_net = QNetwork(state_dim, action_dim).to(device)
        self.target_net.load_state_dict(self.policy_net.state_dict())
        self.target_net.eval()

        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=lr)
        self.loss_fn = nn.SmoothL1Loss()  # Huber loss: more stable than MSE
        self.memory = ReplayBuffer()

    def select_action(self, state):
        if random.random() < self.epsilon:
            return random.randint(0, self.action_dim - 1)

        state_t = torch.FloatTensor(state).unsqueeze(0).to(device)
        with torch.no_grad():
            q_values = self.policy_net(state_t)
        return torch.argmax(q_values, dim=1).item()

    def train_step(self, batch_size=64):
        if len(self.memory) < max(batch_size, self.min_replay_size):
            return

        states, actions, rewards, next_states, dones = self.memory.sample(batch_size)

        states_t = torch.FloatTensor(states).to(device)
        actions_t = torch.LongTensor(actions).unsqueeze(1).to(device)
        rewards_t = torch.FloatTensor(rewards).unsqueeze(1).to(device)
        next_states_t = torch.FloatTensor(next_states).to(device)
        dones_t = torch.FloatTensor(dones).unsqueeze(1).to(device)

        q_values = self.policy_net(states_t).gather(1, actions_t)

        with torch.no_grad():
            max_next_q = self.target_net(next_states_t).max(1, keepdim=True)[0]
            target_q = rewards_t + (1 - dones_t) * self.gamma * max_next_q

        loss = self.loss_fn(q_values, target_q)

        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.policy_net.parameters(), max_norm=5.0)
        self.optimizer.step()

    def update_epsilon(self):
        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)

    def update_target_network(self):
        self.target_net.load_state_dict(self.policy_net.state_dict())


# ----------------------------------------------------------------------------
# Training (on the TRAIN split only)
# ----------------------------------------------------------------------------
train_env = StockTradingEnv(train_features_df, initial_balance=100000)
state_dim = len(STATE_FEATURES)
action_dim = 3  # 0: Sell, 1: Hold, 2: Buy

agent = DQNAgent(state_dim=state_dim, action_dim=action_dim)

episodes = 150
batch_size = 64
target_update_freq = 5

net_worth_history = []
best_net_worth = -np.inf
best_weights = copy.deepcopy(agent.policy_net.state_dict())

print("Starting DQN Model Training...")

for episode in range(1, episodes + 1):
    state = train_env.reset()
    done = False

    while not done:
        action = agent.select_action(state)
        next_state, reward, done = train_env.step(action)

        if done:
            next_state = state

        agent.memory.push(state, action, reward, next_state, done)
        agent.train_step(batch_size)

        state = next_state

    agent.update_epsilon()

    if episode % target_update_freq == 0:
        agent.update_target_network()

    net_worth_history.append(train_env.net_worth)

    # Checkpoint the best-performing greedy-ish episode so evaluation doesn't
    # rely on whatever the last (still epsilon-greedy) episode happened to be.
    if train_env.net_worth > best_net_worth:
        best_net_worth = train_env.net_worth
        best_weights = copy.deepcopy(agent.policy_net.state_dict())

    print(f"Episode {episode:03d}/{episodes} | Ending Portfolio Value: Rs.{train_env.net_worth:,.2f} "
          f"| Epsilon: {agent.epsilon:.4f}")

print("\nTraining Complete!")
print(f"Best training-episode portfolio value: Rs.{best_net_worth:,.2f}")

# Restore the best checkpoint before evaluating on unseen data.
agent.policy_net.load_state_dict(best_weights)
agent.policy_net.eval()

plt.figure(figsize=(10, 5))
plt.plot(net_worth_history, label="DQN Portfolio Value (Train)", color="green")
plt.axhline(y=100000, color="r", linestyle="--", label="Initial Balance (Rs.100,000)")
plt.title("Portfolio Net Worth Progress Across Training Episodes")
plt.xlabel("Episodes")
plt.ylabel("Portfolio Value (Rs.)")
plt.legend()
plt.grid(True)
plt.show()


# ----------------------------------------------------------------------------
# Evaluation on the TEST split (greedy policy, epsilon=0) -- this is what
# actually gets scored against ARIMA via the backtester.
# ----------------------------------------------------------------------------
test_env = StockTradingEnv(test_features_df, initial_balance=100000)
state = test_env.reset()
done = False

actions = []

print("\nRunning Trained Agent on the TEST split to generate actions...")

while not done:
    state_t = torch.FloatTensor(state).unsqueeze(0).to(device)
    with torch.no_grad():
        q_values = agent.policy_net(state_t)
    action = torch.argmax(q_values, dim=1).item()

    actions.append(action)
    state, reward, done = test_env.step(action)

print(f"Collected {len(actions)} actions successfully!")
print(f"Ending Test Portfolio Net Worth (internal env, for reference): Rs.{test_env.net_worth:,.2f}")


# ----------------------------------------------------------------------------
# Backtest, same interface as the notebook
# ----------------------------------------------------------------------------
mapping = {
    2: 1,    # BUY
    1: 0,    # HOLD
    0: -1,   # SELL
}

signals = [mapping[a] for a in actions]

dqn_portfolio = backtester(
    signals,
    test_prices
)

dqn_portfolio.to_csv("dqn_portfolio.csv", index=False)

print("\nSaved backtested results to dqn_portfolio.csv")
